# Generated by Django 4.2.7 on 2023-11-15 15:57

from django.db import migrations, models
import django.db.models.fields.related
import django.db.models.fields.reverse_related


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_delete_libraryauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.ManyToManyField, to='test_app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.fields.reverse_related.ManyToOneRel, to='test_app.library'),
        ),
    ]
