# Generated by Django 4.2.7 on 2023-11-15 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_book_author_alter_librarybook_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.OneToOneField, to='test_app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.library'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.library'),
        ),
    ]
