# Generated by Django 4.2.7 on 2023-11-15 16:31

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_book_author_alter_book_library_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.ManyToManyField, to='test_app.author'),
        ),
    ]
